### ISSUE TITLE
Add MessagePack support

### ISSUE THREAD

**Issue by asbjornu** [okb/Pomona#34]
[MessagePack](http://msgpack.org/) is a light-weight alternative to JSON that it would be nice if Pomona supported.

**Comment by BeeWarloc** [comment]
I like the idea, but I'm not really sure that this will make a great difference. MessagePack support for Newtonsoft.Json seems to be at least partially implemented here https://github.com/Code-Sharp/Newtonsoft.Msgpack, but according to the README it's slower. If bandwidth is a issue, gzipped JSON might be just as good.

I think there would be a lot more to gain by improving how expand works, and implementing caching.

**Comment by asbjornu** [comment]
I agree on your last sentiment. I also think we should gzip everytyhing by default. CPU is cheap these days and reverse proxies can do the work for us, if needed.

**Comment by BeeWarloc** [comment]
Closing this, can reopen in future if an actual need for this arises.
