### ISSUE TITLE
Constructor parameter and property type mismatch

### ISSUE THREAD

**Issue by asbjornu** [okb/Pomona#39]
When a constructor's parameter type doesn't match the type of its target property, a non-wrapped exception like the following is thrown:
```
System.ArgumentException: Got an unexpected exception: Expression of type 'PropertyType' cannot be used for constructor parameter of type 'ParameterType'.
```
It would be nice if this exception was wrapped in an exception with more context and information so it would be easier to debug and fix.

**Comment by BeeWarloc** [comment]
@asbjornu: Do you remember in what scenario this exception is thrown? When POSTing a resource?

**Comment by asbjornu** [comment]
@BeeWarloc Do you expect me to remember such details 14 months after discovering the bug? :smile: Sorry, I have no idea. But it makes sense that this happens on `POST`, yes.

**Comment by BeeWarloc** [comment]
Okay, we'll just reopen this if anyone complains loud enough :smile_cat:

**Comment by asbjornu** [comment]
Yea, I see now that I should have included more context when I reported the bug. Lesson learned, hopefully! :)
